version: '3.8'

services:
  video-downloader:
    build: .
    container_name: video-downloader
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - VD_LOG_LEVEL=info
      - VD_SERVER_PORT=8080
      - VD_DOWNLOAD_MAX_WORKERS=5
      - VD_DOWNLOAD_SAVE_PATH=/app/downloads
      - VD_DATABASE_PATH=/app/data/video-downloader.db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - video-downloader-network

  # Optional: Add a reverse proxy (nginx)
  nginx:
    image: nginx:alpine
    container_name: video-downloader-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - video-downloader
    networks:
      - video-downloader-network
    profiles:
      - proxy

  # Optional: Add a database viewer (adminer)
  adminer:
    image: adminer
    container_name: video-downloader-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=video-downloader-db
    depends_on:
      - video-downloader
    networks:
      - video-downloader-network
    profiles:
      - tools

networks:
  video-downloader-network:
    driver: bridge

volumes:
  downloads:
    driver: local
  data:
    driver: local
  logs:
    driver: local